name: Build & Deploy (Python http.server)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE: ghcr.io/${{ github.repository }}
  CONTAINER_NAME: citizenship-tracker
  INTERNAL_PORT: 8000
  PUBLIC_PORT: 80

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push image
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t $IMAGE:$TAG .
          docker tag $IMAGE:$TAG $IMAGE:latest
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            # Compute tag from GitHub context (available at workflow runtime)
            TAG=${{ github.sha }}
            TAG=${TAG:0:7}

            IMAGE="${{ env.IMAGE }}:${TAG}"
            NAME="${{ env.CONTAINER_NAME }}"
            INT=${{ env.INTERNAL_PORT }}
            PUB=${{ env.PUBLIC_PORT }}

            # (Run once manually on the server: sudo ufw allow 80/tcp)
            # Or keep this with no-password sudo configured:
            # sudo -n ufw allow ${PUB}/tcp || true

            # Safer docker login
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

            docker pull "$IMAGE"

            # Stop/remove previous container if it exists
            if [ "$(docker ps -aq -f name=^${NAME}$)" ]; then
              docker rm -f "$NAME" || true
            fi

            # Run the new container
            docker run -d \
              --name "$NAME" \
              --restart unless-stopped \
              -p "${PUB}:${INT}" \
              "$IMAGE"

            # Clean up old images
            docker image prune -f
